# backend/pdf_services/cloud_storage.py

# generated by Claude
import os
import boto3
from dotenv import load_dotenv

load_dotenv()


# Client Setup part 
s3_client = boto3.client(
    "s3",
    endpoint_url=os.getenv("SUPABASE_S3_ENDPOINT"),
    aws_access_key_id=os.getenv("SUPABASE_S3_ACCESS_KEY"),
    aws_secret_access_key=os.getenv("SUPABASE_S3_SECRET_KEY"),
    region_name=os.getenv("SUPABASE_S3_REGION"),
)

# Specifying where to add the pdf file in which bucket 
BUCKET = os.getenv("SUPABASE_STORAGE_BUCKET")

# This code is for uploading the pdf to bucket 
def upload_file_to_storage(file_bytes: bytes, key: str) -> str:
    s3_client.put_object(
        Bucket=BUCKET,
        Key=key,
        Body=file_bytes,
        ContentType="application/pdf",
    )
    return key


# Downloads and stores the file bytes in a variable 
def download_file_from_storage(key: str) -> bytes:
    obj = s3_client.get_object(Bucket=BUCKET, Key=key)
    return obj["Body"].read()