from sqlalchemy import String , Integer , Column , ForeignKey , DateTime , func
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from Database import base

class Users(base):
    __tablename__ = 'users'
    id = Column(Integer , primary_key = True , index = True)
    username = Column(String , index = True)
    email = Column(String , unique = True , index = True)
    password = Column(String)
    documents = relationship("Documents", back_populates="owner")
    

# generated by claude 
class Documents(base):
    __tablename__ = 'documents'
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    filename = Column(String, nullable=False)
    storage_key = Column(String, nullable=False)   # path in Supabase Storage bucket
    uploaded_at = Column(DateTime(timezone=True), server_default=func.now())

    owner = relationship("Users", back_populates="documents")
    chunks = relationship("DocumentChunks", back_populates="document", cascade="all, delete-orphan")


class DocumentChunks(base):
    __tablename__ = 'document_chunks'
    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False)
    content = Column(String, nullable=False)
    embedding = Column(Vector(384), nullable=False)   # matches bge-small-en-v1.5 output size

    document = relationship("Documents", back_populates="chunks")