# backend/test_storage.py

# generated by claude 
from pdf_services.cloud_storage import upload_file_to_storage, download_file_from_storage

with open("MongoDB.pdf", "rb") as f:
    file_bytes = f.read()

upload_file_to_storage(file_bytes, "test/MongoDB.pdf")
print("Uploaded ✅")

downloaded = download_file_from_storage("test/MongoDB.pdf")
print(f"Downloaded {len(downloaded)} bytes ✅")